### ISSUE TITLE
axios-fetch won't let me intercept 401 failed requests

### ISSUE THREAD

**Issue by thomergil** [lifeomic/axios-fetch#43]
I can't use axios-fetch with together with https://github.com/Flyrell/axios-auth-refresh, because the errors seem to get thrown in a way that cannot be intercepted.

For example,

```
const refreshAuthLogic = (failedRequest: any): Promise<any> => {
...
}

createAuthRefreshInterceptor(axios, refreshAuthLogic, { skipWhileRefreshing: false });

const httpLink = createHttpLink({
  uri: '/backend/graphql/',
  fetch: buildAxiosFetch(axios),
});
```

This works for requests done through axios, but not for apollo requests. The errors that get thrown can't get intercepted by `refreshAuthLogic`.

**Comment by mdlavin** [comment]
I've never seen axios-auth-refresh before. Seems like a very practical helper library. I'm not sure about why it wouldn't work, but I'd be happy to review a PR if you have an environment to reproduce and debug the problem.

**Comment by SimeonC** [comment]
We had the same issue and I eventually tracked it down to this here; https://github.com/lifeomic/axios-fetch/blob/bb0031be6d2c24b42bf6b00360bc30e77e8c2d8b/src/index.js#L26

This line basically stops axios from entering the "error" side of the interceptors chain.

What it should be is this; https://github.com/axios/axios/blob/c7329fefc890050edd51e40e469a154d0117fc55/lib/defaults.js#L79-L81

Which would correctly enter the "error" side of the response interceptor.

I think the reason this line was added was due to the usage of await rather than promises?

**Comment by hogpilot** [comment]
I ran into this same issue and agree with @SimeonC that `validateStatus: () => true` is the culprit.  I think the reason it was there is because of the way the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) is implemented: 

> The Promise returned from fetch() won’t reject on HTTP error status even if the response is an HTTP 404 or 500. Instead, it will resolve normally (with ok status set to false), and it will only reject on network failure or if anything prevented the request from completing.

I think a fix would be to remove the custom `validateStatus` (and thus default to the one referenced by @SimeonC), and wrap the `request` in a `try...catch` instead:

*axios-fetch/src/index.js [starting at line 21]*
``` js

 const config = transfomer({
    url: input,
    method: init.method || 'GET',
    data: init.body instanceof FormData ? init.body : String(init.body),
    headers: lowerCasedHeaders,
    // validateStatus: () => true
  }, input, init);

  // const result = await axios.request(config);
  let result;
  try {
    result = await axios.request(config);
  } catch (err) {
    result = err.response;
  }
```

I'll submit a PR with this change for review.
